### ISSUE TITLE
Not able to access website

### ISSUE THREAD

**Issue by jdee3** [deepclip/deepclip#10]
Hello, can you please let me know how best to access the web version of this tool? https://deepclip.compbio.sdu.dk/ 
Has the link changed? The one you published has been inaccessible for months. 

I saw a previous closed comment this past week within which you stated it's up and running, but I still can't access it. I would greatly appreciate it if you could make this accessible for users. It's a great resource! Thanks in advance.

**Comment by thomaskd** [comment]
You are right, the webserver is inaccessible, thanks for raising the issue. I don't know what the exact problem is yet as the server itself and the docker container are up and running, but I will update here when I know more. When the server is accessible, you can access the DeepCLIP shiny app directly here: https://deepclip-web.compbio.sdu.dk/

**Comment by thomaskd** [comment]
The webserver is now accessible again after much delay, I do apologize for any inconvenience. For the time being, training on the server is disabled.
