### ISSUE TITLE
versions of dependency library

### ISSUE THREAD

**Issue by ekkkkki** [deepclip/deepclip#11]
Hello.

Thanks for your work in DeepClip.
Could you please share the versions of dependency libraries for building DeepClip?  I am facing some bugs training DeepClip and I highly sespect that's caused by library versions out of control.

Best

**Comment by thomaskd** [comment]
Hi

I strongly recommend installing DeepCLIP in a conda environment per the ["Requirements"](https://github.com/deepclip/deepclip#requirements) section.

These specific package versions are installed and seem to work in my python 2.7 conda environment:
biopython                 1.74                     pypi_0    pypi
htseq                     0.11.2                   pypi_0    pypi
matplotlib                2.2.4                    pypi_0    pypi
mkl-service               2.1.0            py27h516909a_0    conda-forge
numpy                     1.16.4                   pypi_0    pypi
scikit-learn              0.20.3                   pypi_0    pypi
scipy                     1.2.2                    pypi_0    pypi

Hope this helps!

Best,
Thomas

**Comment by ekkkkki** [comment]
Thanks for your reply. I managed to run DeepClip by using a Conda environment instead of pyenv+venv. 

Maybe I should create another issue, but it seems hard to access the web server now, especially when doing prediction or training. Just loading...

Anyway, it was really a useful tool. Thanks a lot for your work.

Best
