### ISSUE TITLE
No pfms.json file produced with --predict_PFM_file in cv mode

### ISSUE THREAD

**Issue by scottiadamson** [deepclip/deepclip#3]
I just ran deepclip in cv mode using the --predict_PFM_file flag and it doesn't seem to produce the pfms.json file. It seems like based on the readme that it should be possible. 
Alternatively, is there a simple way to produce the file based on a pre-trained model and prediction function file?
Thanks,
Scott

**Comment by thomaskd** [comment]
Hi Scott, sorry for the confusion, the PFM file is not generated automatically during CV runmode but needs to be generated afterwards. 

You can always generate the pfms.json file with a pretrained model and input sequences in prediction runmode, e.g. using all the positive and background input sequences:
`DeepCLIP.py --runmode predict -P predict_function --sequences all_train_input.fa --predict_PFM_file pfms.json`

Hope this helps,
Thomas

**Comment by scottiadamson** [comment]
That worked. Thanks for the swift response and writing deepclip. 
This seems like it will be a very useful tool for my research and is pretty accessible to a non-expert. Best of luck on publication.
Thanks!
Scott
