### ISSUE TITLE
deepclip website unavailable

### ISSUE THREAD

**Issue by jackhump** [deepclip/deepclip#6]
Hi, apologies if this is the wrong place to ask but I can't seem to access http://deepclip.compbio.sdu.dk/ 

Has the URL changed? I don't want to train my own models, I'm curious to test some SNP sequences against your existing models.

best wishes,

Jack

**Comment by thomaskd** [comment]
Hi Jack

Sorry for the inconvenience, the server hosting the website was down during vacation time so it went undetected for some time unfortunately by us and others, and I didn't get your notification either for some reason. Please don't hesitate to send an email another time :)

Best,
Thomas
