### ISSUE TITLE
error when ran predict mode

### ISSUE THREAD

**Issue by Antidington** [deepclip/deepclip#7]
```
Reading sequences from FASTA file: C17ORF85.fasta
Traceback (most recent call last):
  File "DeepCLIP.py", line 1493, in <module>
    main()
  File "DeepCLIP.py", line 1042, in main
    seq_list, seq_ids_list = read_fasta_file_and_prepare_data(args.sequences)
  File "DeepCLIP.py", line 984, in read_fasta_file_and_prepare_data
    seq += line.rstrip()
UnboundLocalError: local variable 'seq' referenced before assignment
```

**Comment by thomaskd** [comment]
Looks like your fasta file might be misformed as DeepCLIP expects the ">" character as the header of every fasta feature. Could you check your fasta file and make sure it follows the fasta format?

**Comment by thomaskd** [comment]
I'm closing the issue since it seems to have been resolved after checking the input files.

**Comment by Antidington** [comment]
> Looks like your fasta file might be misformed as DeepCLIP expects the ">" character as the header of every fasta feature. Could you check your fasta file and make sure it follows the fasta format?

It is true that there is something wrong with my input file.Now it works.Many thanks!
